# I'm lazy, ok?
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."


# Git
alias gits="git status"

alias gitl="git log --all --oneline --graph --decorate"

alias gitd="git diff"
alias gitds="git diff --staged"
alias gitda="git diff HEAD"
