# I'm lazy, ok?
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."


# Git
alias gits="git status"

alias gitl="git log --all --oneline --graph --decorate"

alias gitda="git diff HEAD"     # Diff All
alias gitds="git diff --staged" # Diff Staged
alias gitdu="git diff"          # Diff Unstaged
